Pre-release version 2.0.0
kevva/os-filter-obj pull request #2
Opened 2017-07-19 14:28 UTC by simonepri

2017-07-20 07:53 UTC, kevva requested changes

2017-07-20 07:53 UTC, kevva commented on test.js
> +import osFilterObj from './';
`import m from '.'`

2017-07-20 07:53 UTC, kevva commented on package.json
> +  "dependencies": {
`dependencies` should be listed before `devDependencies`.

2017-07-20 07:53 UTC, kevva commented on package.json
> +  "version": "2.0.0",
I'll do this manually.

2017-07-20 07:53 UTC, kevva commented on index.js
> +	if (opts && opts.keep) {
This isn't documented.

2017-07-20 07:53 UTC, kevva commented on package.json
> +    "xo": "^0.18.2"
`"xo": "*"`

2017-07-20 12:59 UTC, simonepri commented on test.js
> +import osFilterObj from './';
Also
osFilterObj -> m ??

2017-07-20 13:00 UTC, simonepri commented on index.js
> +	if (opts && opts.keep) {
I was thinking of making an other PR for it, but you're right. Done 👍

2017-07-20 13:18 UTC, kevva commented on test.js
> +import osFilterObj from './';
I use `m` in tests for all my modules to keep consistency.

2017-07-20 16:51 UTC, simonepri commented on test.js
> +import osFilterObj from './';
Makes sense. Done!

2017-07-20 16:53 UTC, simonepri commented on index.js
> +	if (opts && opts.keep) {
You can see the preview here:
https://github.com/simonepri/os-filter-obj

2017-07-24 07:27 UTC, simonepri commented
@kevva any news?

2017-07-24 07:31 UTC, kevva commented
Will take a look at it later today.

2017-07-24 07:33 UTC, simonepri commented
Thank you 🎉 
If other changes are needed, just ask.

2017-07-25 12:54 UTC, merged

2017-07-25 13:03 UTC, kevva commented
Decided to use `keep` as the default behaviour instead.